# SPDX-License-Identifier: GPL-2.0-only
ms912x-y := ms912x_connector.o \
	ms912x_drv.o \
	usb_device.o \
	usb_hal_interface.o \
	usb_hal_sysfs.o \
	usb_hal_thread.o \
	hal_adaptor.o

obj-m += ms912x.o