# SPDX-License-Identifier: GPL-2.0-only
#
#  Makefile for the Bosch C_CAN controller drivers.
#

obj-$(CONFIG_CAN_SDVT_CAN) += cvitek_can.o
obj-$(CONFIG_CAN_SDVT_PLATFORM) += cvitek_can_platform.o
obj-$(CONFIG_CAN_SDVT_BASIC) += sdvt_can_basic.o
